### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/chairo#1]
* When to use Senaca and when not to
* Does this replace all function calls or just the main ones or..?
* Why under hapijs organization? Will it be merged into hapi or become a standard hapi handler or something?
* Do you believe this is a go to way to make nodejs servers?

**Comment by asaf** [comment]
@AdriVanHoudt I personally use it for business logic only, instead of defining Node modules or defining business logic as Hapi helpers.

I don't think this is going to be merged into Hapi as Eran mentioned few times during his presentations, Hapi core should be as minimal as possible, extensions always go to plugins, but I wonder if Chario is used at Walmart in production too =)

I like the concept of micro kernels, Eran has a post about it, you can read more here: 
http://hueniverse.com/2015/06/02/introducing-chairo-a-hapi-js-microservices-plugin/

**Comment by AdriVanHoudt** [comment]
@asaf  read the post. And idd I also like it for the business logic (in theory, I've not actually tried it). Do you have an example of how you use it? Do you use it only for the link between business logic and hapi or even inside the business logic?

**Comment by asaf** [comment]
@AdriVanHoudt It has nothing to do with Hapi, it's all about how you decide to divide your business logic actions, Chario is just a glue plugin between Hapi and Senaca,

I personally have some Senaca plugin per business unit, (such all actions related to 'User' model) and a corresponding Hapi plugin that defines the relevant routes for that business unit,

I do have core actions that other Senaca plugins use to do very core stuff (calling actions within actions is accepted and encouraged).

**Comment by AdriVanHoudt** [comment]
Thanks for the explanation, I'm currently working on the biggest server
I've done yet and with the most business logic and I feel stuff getting
messy and Seneca definitely seems like a solution to keep stuff organized,
thanks

**Comment by asaf** [comment]
@hueniverse I guess you can close this one :-)

**Comment by hueniverse** [comment]
Seneca provides tools to implement microservices and this plugins enables you to integrate this functionality into a hapi server. There is no right/wrong answer about when to use it. It largely depends on how you like to organize your code and how you like to deploy services. Microservices is a big topic.

It is under this organization because it is a hapi plugin and I'm not likely to be the lead maintainer of it for a long time, so it is better served here than in my personal account.
