### ISSUE TITLE
Any plans to upgrade to Seneca.js 3.0 ?

### ISSUE THREAD

**Issue by jeltok** [hapijs/chairo#52]
We use hapi/seneca/chairo for a system that processes several millions of messages per day, and we are very happy with it. We have noticed that Seneca.js team have released a new shiny version 3.0 with several very desirable features and fixes.

Do you have any plans to upgrade to the new version of Seneca.js dependency?

Regards,
Sergey

**Comment by geek** [comment]
@jeltok absolutely! This will be a breaking change, but I am happy for it to be made. 

If you would like to see the update sooner than in a few days then you will likely need to make the change and submit a PR, otherwise it may be a few days before I am able to.

**Comment by StarpTech** [comment]
Hi @geek any chance to upgrade?

**Comment by geek** [comment]
@StarpTech absolutely, I am happy to merge a PR that upgrades to the latest seneca

**Comment by StarpTech** [comment]
Hi @geek of course but Im not really familiar with the internals of senecajs and web. It would be much easier for you to upgrade it. If I can help othwerwise ping me.

**Comment by mazzy89** [comment]
AFAIK it should not be that hard to update to Seneca 3.0. The problem is [here](https://github.com/hapijs/chairo/blob/master/lib/index.js#L62). When the plugin is bootstrapped then it try to export from seneca `web/hapi` but in the version `3.x.x` `seneca-web` has been removed. The idea could be to `web` from this package since now `seneca-web` is a different module. @geek any concerns?

**Comment by geek** [comment]
@mazzy89 that sounds like the best way to proceed. I took a stab at it a few weeks ago and ran into that blockage as well. We will just need to semver major the release with seneca 3 support.

Thanks for your help.

**Comment by mazzy89** [comment]
@geek Submitted a PR
